version: "3.1"

services:
  scheduler:
    build:
      context: ./rascil-no-data
      dockerfile: Dockerfile
    image: timcornwell/rascil-no-data
    hostname: dask-scheduler
    volumes:
      - "${HOME}:${HOME}"
      - "${RASCIL_DATA}:/rascil/data"
    ports:
      - "8786:8786"
      - "8787:8787"
    command: ["dask-scheduler", "--local-directory", "/tmp"]

  worker:
    build:
      context: ./rascil-no-data
      dockerfile: Dockerfile
    image: timcornwell/rascil-no-data
    hostname: dask-worker
    volumes:
    - "${HOME}:${HOME}"
    - "${RASCIL_DATA}:/rascil/data"
      command: ["dask-worker", "--local-directory", "/tmp", "tcp://scheduler:8786"]

  notebook:
    build:
      context: ./rascil-no-data
      dockerfile: Dockerfile
    image: timcornwell/rascil-no-data
    hostname: notebook
    volumes:
      - "${HOME}:${HOME}"
      - "${RASCIL_DATA}:/rascil/data"
    ports:
      - "8888:8888"
    environment:
      - DASK_SCHEDULER_ADDRESS="tcp://scheduler:8786"
    command: ["jupyter-notebook", "--no-browser", "--ip", "0.0.0.0"]
